name: 'mtg_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'mtg_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  mtg_analytics:
    # Apply configurations to all models in this project
    +materialized: view
    
    # Staging models - raw data with minimal transformations
    staging:
      +materialized: view
      +tags: ["staging"]
    
    # Marts - business logic and aggregations
    marts:
      +materialized: table
      +tags: ["marts"]
      
      # Core business entities
      core:
        +materialized: table
      
      # Analytics and reporting
      analytics:
        +materialized: table
