mtg_analytics:
  target: dev
  outputs:
    dev:
      type: sqlite
      # Use the same database as your scraper
      database: 'mtg_cards.db'
      schema: 'main'
      schemas_and_paths:
        main: 'mtg_cards.db'
      schema_directory: '.'
      threads: 4

